export const dynamic = 'force-dynamic';

const mockProperties: Record<string, any> = {
  '1': {
    id: '1',
    name: 'Brooklyn Loft',
    city: 'New York',
    latitude: '40.6501',
    longitude: '-73.9496',
    description: 'Modern loft in the heart of Brooklyn with exposed brick and floor-to-ceiling windows.',
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    valuationUsd: 2500000,
    annualYieldPercentage: 6.5,
    maxShareSupply: 1000,
    sharesOutstanding: 450,
    isArtistHouse: false,
    currentSharePrice: 2500,
    sharesAvailable: 550,
    hourlyRate: 200,
    dailyRate: 1200,
  },
  '2': {
    id: '2',
    name: 'Artist House LA',
    city: 'Los Angeles',
    latitude: '34.0522',
    longitude: '-118.2437',
    description: 'Creative hub and residential space for emerging artists with studio facilities.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    valuationUsd: 3200000,
    annualYieldPercentage: 8.2,
    maxShareSupply: 1200,
    sharesOutstanding: 320,
    isArtistHouse: true,
    currentSharePrice: 2667,
    sharesAvailable: 880,
    hourlyRate: 300,
    dailyRate: 1800,
  },
  '3': {
    id: '3',
    name: 'Miami Recording Studio',
    city: 'Miami',
    latitude: '25.7617',
    longitude: '-80.1918',
    description: 'Professional recording studio with state-of-the-art equipment.',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    valuationUsd: 0,
    annualYieldPercentage: 0,
    maxShareSupply: 0,
    sharesOutstanding: 0,
    isArtistHouse: true,
    currentSharePrice: 0,
    sharesAvailable: 0,
    hourlyRate: 250,
    dailyRate: 1500,
  },
  '4': {
    id: '4',
    name: 'Nashville Music Venue',
    city: 'Nashville',
    latitude: '36.1627',
    longitude: '-86.7816',
    description: 'Live music venue and event space with state-of-the-art acoustics and recording studio.',
    imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    valuationUsd: 1800000,
    annualYieldPercentage: 12.5,
    maxShareSupply: 800,
    sharesOutstanding: 150,
    isArtistHouse: true,
    currentSharePrice: 2250,
    sharesAvailable: 650,
    hourlyRate: 350,
    dailyRate: 2000,
  },
  '5': {
    id: '5',
    name: 'Billionaires Row NYC',
    city: 'New York',
    latitude: '40.7735',
    longitude: '-73.9822',
    description: 'Exclusive penthouse on Manhattan\'s prestigious Billionaires Row with private listening room and world-class recording studio.',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    valuationUsd: 25000000,
    annualYieldPercentage: 9.8,
    maxShareSupply: 5000,
    sharesOutstanding: 2100,
    isArtistHouse: true,
    currentSharePrice: 5000,
    sharesAvailable: 2900,
    hourlyRate: 750,
    dailyRate: 4000,
  },
  '6': {
    id: '6',
    name: 'Billionaires Row London',
    city: 'London',
    latitude: '51.5074',
    longitude: '-0.1278',
    description: 'Ultra-luxury Mayfair mansion with state-of-the-art recording facilities and premium private listening suite.',
    imageUrl: '/studio-soho.png',
    valuationUsd: 28000000,
    annualYieldPercentage: 10.5,
    maxShareSupply: 5500,
    sharesOutstanding: 1800,
    isArtistHouse: true,
    currentSharePrice: 5091,
    sharesAvailable: 3700,
    hourlyRate: 500,
    dailyRate: 2500,
  },
};

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const property = mockProperties[id];

  if (!property) {
    return Response.json({ error: 'Property not found' }, { status: 404 });
  }

  return Response.json(property);
}
